import type { Metadata, Viewport } from "next";
import "./globals.css";
import "../styles/artplayer-liquid-glass.css";
import Navbar from "@/components/Navbar";

export const metadata: Metadata = {
  title: "LongTV",
  description: "Generated by create next app",
  icons: {
    icon: '/favicon.svg',
    shortcut: '/favicon.svg',
    apple: '/favicon.svg',
  },
};

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  maximumScale: 1,
  userScalable: false,
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased">
        <Navbar />
        {children}
      </body>
    </html>
  );
}
